server:
  port: 8188
  servlet:
      context-path: /demo

modeulelist:
  target: _self
  demoUrl: http://microraindrop.com/diyudemo/
  elk:
    logstashUrl: log/Cerebro/Cerebro_overview.html
    elasticUrl: log/Kibana/Kibana_Monitoring.html
    kibanaUrl: log/Kibana/Kibana_Discover.html
  modeuls:
    - moduleId: web3
      moduleName: web3.0
      menus:
        - menuid: ipfs
          menuname: ipfs
          Url: ipfs/IPFSstatus.html
    - moduleId: Setup
      moduleName: 安装与设置
      menus:
        - menuid: SetupMgr
          menuname:
          Url: setup/AmbariclusterInformation.html
    - moduleId: Help
      moduleName: 帮助
      menus:
        - menuid: HelpApplication
          menuname: 综合应用示意图
          Url: helpapplication.html
        - menuid: HelpFramework
          menuname: 软件架构示意图
          Url: helpframework.html
    - moduleId: Download
      moduleName: 下载
      menus:
        - menuid: ClientDownloadMgr
          menuname: 软件下载
          Url: download.html

    - moduleId: cloudsecurity
      moduleName: 下一代云安全方案
      menus:
        - menuid: SDN
          menuname: 软件定义网络
          Url: sdn.html
        - menuid: snwan
          menuname: 软件定义广域网
          Url: sdwan.html
    - moduleId: CloudComputing
      moduleName: 云计算
      menus:
        -  menuid: CloudComputingMgr
           menuname: 云计算管理平台
           Url: openstack/OpenStacklogin.html
        -  menuid: CloudComputingMonitor
           menuname: 云计算监控平台
           Url: openstack/OpenstackcloudsGrafana.html
    - moduleId: CloudStorage
      moduleName: 云存储
      menus:
        - menuid: CloudStorageMgr
          menuname: 云存储管理平台
          Url: ceph/openATTIClogin.html
        - menuid: CloudStorageMonitor
          menuname: 云存储监控平台
          Url: ceph/CephClusterGrafana.html
        - menuid: CloudStorageMonitor
          menuname: 服务器监控平台
          Url: ceph/NodeExporterDashboard.html
    - moduleId: MicroSvc
      moduleName: 微服务
      menus:
        - menuid: MicroSvcMgr
          menuname: 微服务管理平台
          Url: kubernetes/KubernetesDashboardoverview.html
        - menuid: MicroSvcMonitor
          menuname: 微服务监控平台
          Url: kubernetes/KubernetesGrafanaMonitoring.html
    - moduleId: BigDate
      moduleName: 大数据
      menus:
        - menuid: BigDateMgr
          menuname: 大数据管理平台
          Url: ambari/Ambarilogin.html
        - menuid: BigDateMonitor
          menuname: 大数据监控平台
          Url: ambari/Ambaridashboardmetrics.html
    - moduleId: Hyperledger
      moduleName: 区块链
      menus:
        - menuid: HyperledgerMgr
          menuname: 区块链管理平台
          Url: hyperledgerexplorer/HyperledgerExplorerdashboard.html
        - menuid: HyperledgerMonitor
          menuname: 区块链监控平台
          Url: hyperledgerMonitor.html
    - moduleId: IOT
      moduleName: 物联网
      menus:
        - menuid: IOTMgr
          menuname: 物联网管理平台
          Url: thingsboard/ThingsBoardlogin.html
        - menuid: IOTMonitor
          menuname: 物联网监控平台
          Url: thingsboard/ThingsBoardwidgets-bundles.html
    - moduleId: AI
      moduleName: 人工智能
      menus:
        - menuid: AIMgr
          menuname: 人工智能管理平台
          Url: ai.html
        - menuid: IOTMonitor
          menuname: 人工智能监控平台
          Url: aimonitor.html
    - moduleId: Log
      moduleName: 日志汇总监控
      menus:
        - menuid: LogMgr
          menuname: 日志汇总
          Url: ./elkList
        - menuid: LogMonitor
          menuname: 日志监控
          Url: ./monitorList
    - moduleId: Backup
      moduleName: 容灾备份
      menus:
        - menuid: BackupMgr
          menuname: 容灾备份管理
          Url: backup/backup.html
        - menuid: BackupMonitor
          menuname: 容灾备份监控
          Url: backup/status.html